### ISSUE TITLE
Getting exceptions - _create_widget 'Neither Tkinter nor ttk have a widget named: ', name

### ISSUE THREAD

**Issue by mssguavus** [tmetsch/pytkgen#7]
> > > import tkgen.gengui
> > > 
> > > root = tkgen.gengui.TkJson(mj, title = 'Some test gui...')
> > > Traceback (most recent call last):
> > >   File "/Users/mohammad.siddiqui/Downloads/pytkgen-master/tkgen/gengui.py", line 140, in _create_widget
> > >     tkinter, name) if self.preferTk else getattr(ttk, name)
> > > AttributeError: 'module' object has no attribute 'env'
> > > Traceback (most recent call last):
> > >   File "/Users/mohammad.siddiqui/Downloads/pytkgen-master/tkgen/gengui.py", line 146, in _create_widget
> > >     ttk, name) if self.preferTk else getattr(tkinter, name)
> > > AttributeError: 'module' object has no attribute 'env'
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/mohammad.siddiqui/Downloads/pytkgen-master/tkgen/gengui.py", line 97, in __init__
> > >     self.create_widgets(self, user_interface)
> > >   File "/Users/mohammad.siddiqui/Downloads/pytkgen-master/tkgen/gengui.py", line 117, in create_widgets
> > >     widget = self._create_widget(name, parent, current)
> > >   File "/Users/mohammad.siddiqui/Downloads/pytkgen-master/tkgen/gengui.py", line 151, in _create_widget
> > >     'Neither Tkinter nor ttk have a widget named: ', name)
> > > AttributeError: ('Neither Tkinter nor ttk have a widget named: ', u'env')

**Comment by tmetsch** [comment]
Hi - can you post some details about the environment you are using? pyhton version and tk version? Thanks!

**Comment by mssguavus** [comment]
Yeah Sure.
I am using Macbook Pro (Captain)
$ python -V
Python 2.7.10
>>> import Tkinter
>>> Tkinter.__version__ 
'$Revision: 81008 $'

**Comment by tmetsch** [comment]
This is now fixed on the master branch - there was a superfluos dump of trace.
