### ISSUE TITLE
Question: combobox support

### ISSUE THREAD

**Issue by Dave-Vallance** [tmetsch/pytkgen#8]
Hello,
  Great project! This really helps speed up prototyping and keeping clutter out of the main python files. 

Is there currently support or helper functions for ttk.Combobox() or OptionMenu() being defined in the json file?

I see you have support and examples for creating main menus (through root.create_menu().)

To add a Combobox I am currently doing the following. Perhaps you can comment if there is something I am missing or a better way to do this? It works but I would love to tidy it up.

`

    options = ['Option 1', 'Option 2']
    option_var = tk.StringVar()
    option_var.set(data_provider_options[0])
    options_frame = root.get('options_label_frame')
    opts_combo_box = ttk.Combobox(options_frame,textvariable=option_var)
    opts_combo_box.grid(
        row=0,
        column=0,
        sticky=tk.N+tk.E+tk.W
    )
    opts_combo_box['values'] = options
    opts_combo_box.bind('<<ComboboxSelected>>', myFunction)
`

**Comment by tmetsch** [comment]
Hi, 

I'm glad this little tool helps you :-)

Yes Combobox etc would be supported. You can define them like this in the json files:

        "Combobox": {
            "name": "combo",
            "values": ["option 1", "option 2"],
            "column": 1,
            "row": 0
        }

obviously the _values_ definition is optional. Now in the python code you can retrieve the the Combobox as usual:

    combobox = root.get('combo')

If you want to set the options in the code you can do the following:

    combobox['values'] = ['option 1', 'option 2']

Hope this help.

The complete json example:

    {
        "LabelFrame":{
            "text":"Combobox example",
            "weight":1,
            "column": 0,
            "columnspan": 3,
            "row": 0,
            "Label":{
                "text":"Entry:",
                "column": 0,
                "row": 0
            },
            "Combobox": {
                "name": "combo",
                "values": ["option 1", "option 2"],
                "column": 1,
                "row": 0
            }
        },
        "Label":{
            "name":"empty",
            "text":" ",
            "column": 0,
            "row": 1,
            "colweight":1
            },
        "Button":[        
            {
                "name":"ok",
                "text":"OK",
                "column": 1,
                "row": 1
            },
            {
                "name":"cancel",
                "text":"Cancel",
                "column": 2,
                "row": 1
            }
        ]
    }

And the corresponding python code:

    import tkgen.gengui

    if __name__ == '__main__':
        root = tkgen.gengui.TkJson('example_combobox.json', title='Some test gui...')

        def ok(event=None):
            print(combobox.get())
            root.destroy()

        # combox box.
        combobox = root.get('combo')
        combobox['values'] = ['bla 1', 'bla 2']

        # add button behaviour
        root.button('ok', ok)
        root.button('cancel', root.destroy)

        root.mainloop()

**Comment by Dave-Vallance** [comment]
Thank you very much for the detailed reply! I will give it a go.
